/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewIndexRouteImport } from './routes/preview.index'
import { Route as RunDemoAnkerRouteImport } from './routes/run.demo-anker'
import { Route as RunIdRouteImport } from './routes/run.$id'
import { Route as PreviewRunSampleRouteImport } from './routes/preview.run-sample'
import { Route as PreviewFitDiagnosisPreRouteImport } from './routes/preview.fit-diagnosis-pre'
import { Route as PreviewFitDiagnosisPostRouteImport } from './routes/preview.fit-diagnosis-post'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewRoute,
} as any)
const RunDemoAnkerRoute = RunDemoAnkerRouteImport.update({
  id: '/run/demo-anker',
  path: '/run/demo-anker',
  getParentRoute: () => rootRouteImport,
} as any)
const RunIdRoute = RunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRunSampleRoute = PreviewRunSampleRouteImport.update({
  id: '/run-sample',
  path: '/run-sample',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewFitDiagnosisPreRoute = PreviewFitDiagnosisPreRouteImport.update({
  id: '/fit-diagnosis-pre',
  path: '/fit-diagnosis-pre',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewFitDiagnosisPostRoute = PreviewFitDiagnosisPostRouteImport.update({
  id: '/fit-diagnosis-post',
  path: '/fit-diagnosis-post',
  getParentRoute: () => PreviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/experiences': typeof ExperiencesRoute
  '/preview': typeof PreviewRouteWithChildren
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/preview/fit-diagnosis-post': typeof PreviewFitDiagnosisPostRoute
  '/preview/fit-diagnosis-pre': typeof PreviewFitDiagnosisPreRoute
  '/preview/run-sample': typeof PreviewRunSampleRoute
  '/run/$id': typeof RunIdRoute
  '/run/demo-anker': typeof RunDemoAnkerRoute
  '/preview/': typeof PreviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/experiences': typeof ExperiencesRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/preview/fit-diagnosis-post': typeof PreviewFitDiagnosisPostRoute
  '/preview/fit-diagnosis-pre': typeof PreviewFitDiagnosisPreRoute
  '/preview/run-sample': typeof PreviewRunSampleRoute
  '/run/$id': typeof RunIdRoute
  '/run/demo-anker': typeof RunDemoAnkerRoute
  '/preview': typeof PreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/experiences': typeof ExperiencesRoute
  '/preview': typeof PreviewRouteWithChildren
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/preview/fit-diagnosis-post': typeof PreviewFitDiagnosisPostRoute
  '/preview/fit-diagnosis-pre': typeof PreviewFitDiagnosisPreRoute
  '/preview/run-sample': typeof PreviewRunSampleRoute
  '/run/$id': typeof RunIdRoute
  '/run/demo-anker': typeof RunDemoAnkerRoute
  '/preview/': typeof PreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/experiences'
    | '/preview'
    | '/resume'
    | '/settings'
    | '/setup'
    | '/preview/fit-diagnosis-post'
    | '/preview/fit-diagnosis-pre'
    | '/preview/run-sample'
    | '/run/$id'
    | '/run/demo-anker'
    | '/preview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/experiences'
    | '/resume'
    | '/settings'
    | '/setup'
    | '/preview/fit-diagnosis-post'
    | '/preview/fit-diagnosis-pre'
    | '/preview/run-sample'
    | '/run/$id'
    | '/run/demo-anker'
    | '/preview'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/experiences'
    | '/preview'
    | '/resume'
    | '/settings'
    | '/setup'
    | '/preview/fit-diagnosis-post'
    | '/preview/fit-diagnosis-pre'
    | '/preview/run-sample'
    | '/run/$id'
    | '/run/demo-anker'
    | '/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  ExperiencesRoute: typeof ExperiencesRoute
  PreviewRoute: typeof PreviewRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  RunIdRoute: typeof RunIdRoute
  RunDemoAnkerRoute: typeof RunDemoAnkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/': {
      id: '/preview/'
      path: '/'
      fullPath: '/preview/'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/run/demo-anker': {
      id: '/run/demo-anker'
      path: '/run/demo-anker'
      fullPath: '/run/demo-anker'
      preLoaderRoute: typeof RunDemoAnkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$id': {
      id: '/run/$id'
      path: '/run/$id'
      fullPath: '/run/$id'
      preLoaderRoute: typeof RunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/run-sample': {
      id: '/preview/run-sample'
      path: '/run-sample'
      fullPath: '/preview/run-sample'
      preLoaderRoute: typeof PreviewRunSampleRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/fit-diagnosis-pre': {
      id: '/preview/fit-diagnosis-pre'
      path: '/fit-diagnosis-pre'
      fullPath: '/preview/fit-diagnosis-pre'
      preLoaderRoute: typeof PreviewFitDiagnosisPreRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/fit-diagnosis-post': {
      id: '/preview/fit-diagnosis-post'
      path: '/fit-diagnosis-post'
      fullPath: '/preview/fit-diagnosis-post'
      preLoaderRoute: typeof PreviewFitDiagnosisPostRouteImport
      parentRoute: typeof PreviewRoute
    }
  }
}

interface PreviewRouteChildren {
  PreviewFitDiagnosisPostRoute: typeof PreviewFitDiagnosisPostRoute
  PreviewFitDiagnosisPreRoute: typeof PreviewFitDiagnosisPreRoute
  PreviewRunSampleRoute: typeof PreviewRunSampleRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewFitDiagnosisPostRoute: PreviewFitDiagnosisPostRoute,
  PreviewFitDiagnosisPreRoute: PreviewFitDiagnosisPreRoute,
  PreviewRunSampleRoute: PreviewRunSampleRoute,
  PreviewIndexRoute: PreviewIndexRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  ExperiencesRoute: ExperiencesRoute,
  PreviewRoute: PreviewRouteWithChildren,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  RunIdRoute: RunIdRoute,
  RunDemoAnkerRoute: RunDemoAnkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
